let system_name = system('uname')

if system_name =~ "Darwin"
  set guifont=JetBrainsMono\ Nerd\ Font:h20
  let g:Lf_ShowDevIcons = 1
  let g:airline#extensions#tabline#left_sep = ''
  let g:airline#extensions#tabline#left_alt_sep = ''
  let g:airline#extensions#tabline#right_sep = ''
  let g:airline#extensions#tabline#right_alt_sep = ''
elseif system_name =~ "Linux"
  set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 16
elseif has('win32')
  set guifont=DejaVu\ Sans\ Mono\ for\ Powerline:h18
endif
