# vim: set ft=zsh:

if [[ "$(uname)" == "Darwin" ]]; then
  export EDITOR=/usr/local/bin/nvim
  export SHELL=/usr/local/bin/zsh
fi
export VISUAL="$EDITOR"

PROFILE_LOCAL=~/.profile_local
if [[ -f "$PROFILE_LOCAL" ]]; then
  source ~/.profile_local
fi
