# vim: set ft=zsh:

if [[ "$(uname)" == "Darwin" ]]; then
  export EDITOR=/usr/local/bin/nvim
  export SHELL=/usr/local/bin/zsh
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
fi
export VISUAL="$EDITOR"
