### start of oh-my-zsh ###
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gallois"

plugins=(git pyenv zsh-autosuggestions zsh-syntax-highlighting thefuck vi-mode)

source $ZSH/oh-my-zsh.sh

# Put plugins config after this line
# zsh-autosuggestions
bindkey '^ ' autosuggest-accept

# vi-mode
VI_MODE_SET_CURSOR=true
### end of oh-my-zsh ###

# Load common settings
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'
